language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:

script:
  - npm run lint
  - npm run test-ci
  - npm run build -- --prod --baseHref=https://andrejepam.github.io/SportsBook/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/SportsBook
  on:
    branch: master
